name: Fetch Stock Data

on:
  workflow_dispatch:
    inputs:
      ticker:
        description: 'Stock ticker symbol'
        required: true
        default: 'AAPL'

jobs:
  fetch_data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install dependencies
      run: |
        Rscript -e 'install.packages(c("quantmod"))'

    - name: Fetch stock data
      run: |
        Rscript -e "library(quantmod); getSymbols('${{ github.event.inputs.ticker }}', src = 'yahoo'); write.csv(get(${github.event.inputs.ticker}), '${{ github.event.inputs.ticker }}.csv')"

    - name: Commit and push data
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add ${{ github.event.inputs.ticker }}.csv
        git commit -m 'Add stock data for ${{ github.event.inputs.ticker }}'
        git push
